# Generated by Django 3.2 on 2023-04-18 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeptDetails',
            fields=[
                ('deptID', models.CharField(choices=[('CSE', 'CSE'), ('ICT', 'ICT'), ('ECE', 'ECE'), ('MECH', 'MECH')], default='CSE', max_length=10, primary_key=True, serialize=False)),
                ('DeptName', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='FAC',
            fields=[
                ('FacultyID', models.CharField(choices=[('F101', 'F101'), ('F305', 'F305'), ('F403', 'F403'), ('F106', 'F106'), ('F202', 'F202'), ('F204', 'F204'), ('F205', 'F205'), ('F401', 'F401'), ('F405', 'F405'), ('F104', 'F104'), ('F406', 'F406'), ('F105', 'F105'), ('F306', 'F306'), ('F103', 'F103'), ('F404', 'F404'), ('F102', 'F102'), ('F201', 'F201'), ('F302', 'F302'), ('F303', 'F303'), ('F206', 'F206'), ('F304', 'F304'), ('F402', 'F402'), ('F301', 'F301'), ('F203', 'F203')], default='F101', max_length=10, primary_key=True, serialize=False)),
                ('Facultyname', models.CharField(max_length=50)),
                ('deptID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='p2.deptdetails')),
            ],
            options={
                'db_table': 'Faculty_Info',
            },
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('rno', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('age', models.DecimalField(decimal_places=2, max_digits=5)),
                ('deptID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='p2.deptdetails')),
            ],
            options={
                'db_table': 'Student_Info',
            },
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.CharField(choices=[('C101', 'C101'), ('C102', 'C102'), ('C103', 'C103'), ('C201', 'C201'), ('C202', 'C202'), ('C203', 'C203'), ('C301', 'C301'), ('C302', 'C302'), ('C303', 'C303'), ('C401', 'C401'), ('C402', 'C402'), ('C403', 'C403')], default='TOC', max_length=50)),
                ('q1', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='2', max_length=50)),
                ('q2', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='2', max_length=50)),
                ('q3', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='2', max_length=50)),
                ('q4', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='2', max_length=50)),
                ('q5', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='2', max_length=50)),
                ('comment', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('FacultyID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='p2.fac')),
                ('rno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='p2.studentinfo')),
            ],
            options={
                'db_table': 'Feedback_Table',
            },
        ),
        migrations.CreateModel(
            name='COU',
            fields=[
                ('CID', models.CharField(choices=[('C101', 'C101'), ('C102', 'C102'), ('C103', 'C103'), ('C201', 'C201'), ('C202', 'C202'), ('C203', 'C203'), ('C301', 'C301'), ('C302', 'C302'), ('C303', 'C303'), ('C401', 'C401'), ('C402', 'C402'), ('C403', 'C403')], default='C101', max_length=10, primary_key=True, serialize=False)),
                ('Course', models.CharField(max_length=50)),
                ('deptID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='p2.deptdetails')),
            ],
            options={
                'db_table': 'Course_Info',
            },
        ),
    ]
