# Generated by Django 3.2 on 2023-04-18 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='Course',
        ),
        migrations.AddField(
            model_name='feed',
            name='CID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='p2.cou'),
        ),
        migrations.AlterField(
            model_name='fac',
            name='FacultyID',
            field=models.CharField(choices=[('F302', 'F302'), ('F205', 'F205'), ('F301', 'F301'), ('F305', 'F305'), ('F105', 'F105'), ('F405', 'F405'), ('F401', 'F401'), ('F103', 'F103'), ('F102', 'F102'), ('F403', 'F403'), ('F406', 'F406'), ('F106', 'F106'), ('F304', 'F304'), ('F203', 'F203'), ('F206', 'F206'), ('F402', 'F402'), ('F303', 'F303'), ('F104', 'F104'), ('F204', 'F204'), ('F201', 'F201'), ('F306', 'F306'), ('F101', 'F101'), ('F404', 'F404'), ('F202', 'F202')], default='F101', max_length=10, primary_key=True, serialize=False),
        ),
    ]
